language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run auth_server sh -c "mvn test"
  - docker-compose run distribution_res_server sh -c "mvn-test"
