language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run authservertest sh -c "./wait-for-it.sh postgres:5432 -t 60 -- mvn clean test"
  - docker-compose run distribution_res_server_test sh -c "./wait-for-it.sh authservertest:5432 -t 60 -- mvn clean test"

