version: '3'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./postgres_scripts/db_creation.sql:/docker-entrypoint-initdb.d/1-init.sql
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
        - '3050:80'
  authserver:
    build: 
      dockerfile: Dockerfile.dev
      context: ./emles_oauth_server
    volumes:
      - ./emles_oauth_server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=emles_oauth2
      - PG_TEST_DATABASE=emles_oauth2_test
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTH_SERVER_PORT=8081
    ports:
      - '8000:8081'
     # - '5005:5005' uncomment to use debugger
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "-t", "60", "--", "mvn", "spring-boot:run"]
  distribution_res_server:
    build: 
      dockerfile: Dockerfile.dev
      context: ./emles_distribution_resource_server
    volumes:
      - ./emles_distribution_resource_server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=emles_oauth2
      - PG_TEST_DATABASE=emles_oauth2_test
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8083
    ports:
      - '8001:8083'
     # - '5005:5005' uncomment to use debugger
    depends_on:
      - postgres
      - redis
      - authserver
    command: ["./wait-for-it.sh", "postgres:5432", "-t", "60", "--", "mvn", "spring-boot:run"]
  authservertest:
    build: 
      dockerfile: Dockerfile.dev
      context: ./emles_oauth_server
    volumes:
      - ./emles_oauth_server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=emles_oauth2_test
      - PG_TEST_DATABASE=emles_oauth2_test
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTH_SERVER_PORT=8084
    ports:
      - '8002:8084'
     # - '5005:5005' uncomment to use debugger
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "-t", "60", "--", "mvn", "spring-boot:run"]
  distribution_res_server_test:
    build: 
      dockerfile: Dockerfile.dev
      context: ./emles_distribution_resource_server
    volumes:
      - ./emles_distribution_resource_server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=emles_oauth2_test
      - PG_TEST_DATABASE=emles_oauth2_test
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8085
    ports:
      - '8003:8085'
     # - '5005:5005' uncomment to use debugger
    depends_on:
      - postgres
      - redis
      - authservertest
    command: ["./wait-for-it.sh", "postgres:5432", "-t", "60", "--", "mvn", "spring-boot:run"]